name: Varbase Content Base
description: A foundational recipe for content structure and management in Varbase. Provides core content configuration for content types, taxonomy vocabularies, block content, menu system, path aliases, and essential content-related modules.
type: Varbase Content
install:
  - node
  - taxonomy
  - text
  - views
  - field
  - block
  - block_content
  - config
  - datetime
  - file
  - image
  - options
  - path
  - entity
  - ctools
  - ctools_block
  - ctools_views
  - token
  - token_filter
  - better_exposed_filters
  - date_filter
  - field_group
  - smart_trim
  - advanced_text_formatter
  - block_class
  - contextual
  - diff
  - eca
  - modeler_api
  - bpmn_io
  - eca_ui
  - eca_base
  - eca_config
  - eca_content
  - eca_form
  - eca_misc
  - eca_user
  - eca_render
  - eca_access
  - eca_cache
  - eca_file
  - eca_menu
  - eca_queue
  - eca_views
  - eca_log
  - eca_endpoint
  - menu_ui
  - menu_link_content
  - filter
  - field_ui
  - help
  - menu_block
  - views_infinite_scroll
  - entity_browser
  - entity_usage
  - entity_browser
  - entityqueue
  - entityqueue_form_widget
  - inline_entity_form
  - inline_form_errors
  - menu_position
  - tagify
  - rabbit_hole
  - vmi
  - varbase_components
config:
  strict:
    - field.storage.node.body
    - field.storage.node.field_description
    - field.storage.node.field_categories
    - field.storage.block_content.field_description
    - field.storage.taxonomy_term.field_description
  actions:
    tagify.settings:
      simpleConfigUpdate:
        set_default_widget: true
    user.role.anonymous:
      grantPermissions:
        - 'access content'
        - 'view media'
    user.role.authenticated:
      grantPermissions:
        - 'access content'
        - 'access user profiles'
        - 'view media'
        - 'view own unpublished content'
    user.role.content_editor:
      grantPermissions:
        - 'access contextual links'
        - 'access content overview'
        - 'view all revisions'
        - 'view own unpublished content'
        - 'access taxonomy overview'
        - 'administer menu'
        - 'create canvas_page'
        - 'edit canvas_page'
        - 'administer url aliases'
        - 'create any term'
        - 'create terms in tags'
        - 'create url aliases'
        - 'edit terms in tags'
        - 'select terms in tags'
        - 'select unpublished terms in tags'
        - 'use menu link attributes'
        - 'use views bulk edit'
        - 'view any term'
        - 'view any term name'
        - 'view any unpublished term'
        - 'view any unpublished term name'
        - 'view any vocabulary name'
        - 'view term names in tags'
        - 'view terms in tags'
        - 'view unpublished term names in tags'
        - 'view unpublished terms in tags'
        - 'view vocabulary labels'
        - 'view vocabulary name of tags'
    user.role.content_admin:
      grantPermissions:
        - 'access content overview'
        - 'access contextual links'
        - 'access taxonomy overview'
        - 'administer folders'
        - 'create canvas_page'
        - 'edit canvas_page'
        - 'administer menu'
        - 'administer page template'
        - 'administer patterns'
        - 'administer taxonomy'
        - 'create any term'
        - 'create terms in tags'
        - 'create url aliases'
        - 'delete any term'
        - 'delete terms in tags'
        - 'edit terms in tags'
        - 'manipulate all entityqueues'
        - 'publish auto-saves'
        - 'reorder terms in any vocabulary'
        - 'reset any vocabulary'
        - 'revert all revisions'
        - 'select any term'
        - 'select any unpublished term'
        - 'select terms in tags'
        - 'select unpublished terms in tags'
        - 'update any term'
        - 'use menu link attributes'
        - 'use views bulk edit'
        - 'view all revisions'
        - 'view any term'
        - 'view any term name'
        - 'view any unpublished term'
        - 'view any unpublished term name'
        - 'view any vocabulary name'
        - 'view own unpublished content'
        - 'view term names in tags'
        - 'view terms in tags'
        - 'view unpublished term names in tags'
        - 'view unpublished terms in tags'
        - 'view vocabulary labels'
        - 'view vocabulary name of tags'
    user.role.seo_admin:
      grantPermissions:
        - 'access content overview'
        - 'access contextual links'
        - 'access taxonomy overview'
        - 'administer menu'
        - 'administer url aliases'
        - 'create any term'
        - 'create terms in tags'
        - 'create url aliases'
        - 'edit terms in tags'
        - 'select terms in tags'
        - 'select unpublished terms in tags'
        - 'use menu link attributes'
        - 'use views bulk edit'
        - 'view all revisions'
        - 'view any term'
        - 'view any term name'
        - 'view any unpublished term'
        - 'view any unpublished term name'
        - 'view any vocabulary name'
        - 'view own unpublished content'
        - 'view term names in tags'
        - 'view terms in tags'
        - 'view unpublished term names in tags'
        - 'view unpublished terms in tags'
        - 'view vocabulary labels'
        - 'view vocabulary name of tags'
    user.role.site_admin:
      grantPermissions:
        - 'access content overview'
        - 'access contextual links'
        - 'access taxonomy overview'
        - 'administer block classes'
        - 'administer components'
        - 'administer content menu items'
        - 'administer content templates'
        - 'administer folders'
        - 'administer menu'
        - 'administer page template'
        - 'administer patterns'
        - 'administer social-media-menu menu items'
        - 'administer symfony_mailer_lite configuration'
        - 'administer taxonomy'
        - 'create any term'
        - 'create canvas_page'
        - 'create terms in tags'
        - 'create url aliases'
        - 'delete any term'
        - 'delete canvas_page'
        - 'delete terms in tags'
        - 'edit canvas_page'
        - 'edit terms in tags'
        - 'manipulate all entityqueues'
        - 'manipulate entityqueues'
        - 'publish auto-saves'
        - 'reorder terms in any vocabulary'
        - 'reorder terms in tags'
        - 'reset any vocabulary'
        - 'revert all revisions'
        - 'select any term'
        - 'select any unpublished term'
        - 'select terms in tags'
        - 'select unpublished terms in tags'
        - 'taxonomy manager export csv for tags'
        - 'taxonomy manager export list for tags'
        - 'update any term'
        - 'use menu link attributes'
        - 'use views bulk edit'
        - 'view all revisions'
        - 'view any term'
        - 'view any term name'
        - 'view any unpublished term'
        - 'view any unpublished term name'
        - 'view any vocabulary name'
        - 'view own unpublished content'
        - 'view term names in tags'
        - 'view terms in tags'
        - 'view unpublished term names in tags'
        - 'view unpublished terms in tags'
        - 'view vocabulary labels'
        - 'view vocabulary name of tags'
